[package]
name = "functional-rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "borrowing"
path = "src/borrowing.rs"

[[bin]]
name = "closure"
path = "src/closure.rs"

[[bin]]
name = "currying"
path = "src/currying.rs"

[dependencies]
